sculpin:
sculpin_theme:
    theme: sculpin/bootstrap-3-blog-theme
sculpin_content_types:

    guides:
        type: path
        path: _guides
        singular_name: guide
        enabled: true
        taxonomies:
            - parent_guide
            - framework
        permalink: guides/:slug_title/

    common-tasks:
        type: path
        path: _common-tasks
        singular_name: common-task
        enabled: true
        taxonomies:
            - tools
            - framework
        permalink: common-tasks/:slug_title/

    tools:
        type: path
        path: _tools
        singular_name: tool
        enabled: true
        taxonomies:
            - framework
        permalink: tools/:slug_title/

    sites:
        type: path
        path: _sites
        singular_name: site
        enabled: true
        taxonomies:
            - framework
        permalink: sites/:slug_title/
