sculpin:
sculpin_theme:
    theme: sculpin/bootstrap-3-blog-theme
sculpin_content_types:

    documents:
        type: path
        path: articles
        singular_name: document
        enabled: true
        taxonomies:
            - parent_guide
            - framework
        permalink: pretty
