services:
    sculpin_content_types.types.documents.collection.sorter:
        class: Sculpin\Contrib\ProxySourceCollection\Sorter\MetaSorter
        arguments:
             - title
    sculpin_taxonomies.taxonomies.categories.collection.sorter:
        class: Sculpin\Contrib\ProxySourceCollection\Sorter\MetaSorter
        arguments:
             - title
