version: 2
dependencies:
  cache_directories:
    - ~/.composer/cache
    - ~/build/vendor
    - ~/build/node_modules
jobs:
  build:
    docker:
      - image: pantheonsystems/documentation:circle
    working_directory: ~/build
    steps:
      - checkout
      - run:
          name: Generate build
          command: |
            npm install
            ./node_modules/.bin/grunt
            /documentation/bin/sculpin generate --env=prod --quiet
      - run:
          name: Deploy Multidev environment
          command: bash ./scripts/deploy-multidev.sh
      - run:
          name: Start Ghost Driver
          command: phantomjs --webdriver=8643
          background: true
      - run:
          name: Start Sculpin
          command: /documentation/bin/sculpin server
          background: true
      - run:
          name: Speedtest
          command: |
            echo
            # Run sitespeed.io performance testing.
            mkdir ~/build/artifacts
            bash scripts/run-sitespeed-test.sh
      - run:
          name: Behat
          command: |
            /documentation/bin/behat
      - run:
          name: a11y
          command: |
            /documentation/node_modules/.bin/grunt test
      - run:
          name: Merge Conflicts
          command: |
            scripts/merge_conflicts.sh
      - run:
          name: htmlProofer
          command: |
            htmlproofer --assume-extension  ./output_dev/ --disable-external true
      - store_artifacts:
          path: ~/build/sitespeed-result

      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "masterblaster" ]; then
              scripts/deploy-live.sh
            fi


# artifacts need to be done sitespeed-result
# deployment command for master: bash scripts/deploy-live.sh

experimental:
  notify:
    branches:
      only:
        - master
